spring:
  config:
    import: "./confidence/application-secret.yml"
    activate:
      on-profile: prod

# 배포전용 DB로연결
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k10c104.p.ssafy.io:${prod.datasource.port}/seolo?serverTimezone=Asia/Seoul
    username: ${prod.datasource.username}
    password: ${prod.datasource.password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  jwt:
    access: ${common.redis.session-store.accessKey}
    refresh: ${common.redis.session-store.refreshKey}
    accesstime: ${common.redis.session-store.accessLifetime}
    refreshtime: ${common.redis.session-store.refreshLifetime}
  data:
    redis:
      host: k10c104.p.ssafy.io
      port: ${common.redis.session-store.port}
  cloud:
    aws:
      credentials:
        accessKey: ${common.aws.credentials.access-key}
        secretKey: ${common.aws.credentials.secret-key}
      region:
        static: ${common.aws.region.static}
      s3:
        bucket: ${common.aws.s3.bucket}

